{% set name = "openscm-runner" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a43c68861be276bf3672fc35d46fcba9aeac739fbe7777ec8e1668786f5d3735

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm

  run:
    - python >={{ python_min }}
    - click
    - openscm-units >=0.5.0
    - pyam >=1.2
    - python-dotenv
    - scmdata >=0.7.4
    - tqdm
    - importlib-metadata

test:
  imports:
    - openscm_runner
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -c "import openscm_runner; print(openscm_runner.__version__); assert openscm_runner.__version__ == '{{ version }}'"

about:
  home: https://github.com/openscm/openscm-runner
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Thin wrapper to run simple climate models (emissions driven runs only)
  doc_url: https://openscm-runner.readthedocs.io/en/stable/
  dev_url: https://github.com/openscm/openscm-runner

extra:
  recipe-maintainers:
    - znicholls
